/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usacshop.vista;

/**
 *
 * @author Katherin Yasmin
 */
import usacshop.vista.AdminView;
import usacshop.vista.VendedorView;
import usacshop.vista.ClienteView;
import usacshop.controlador.VendedorControlador;



import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.*;

public class LoginView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("USAC SHOP INICIO DE SESION");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioIngresar = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Sancarlista Shop");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("USUARIO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("CONTRASEÑA");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usacshop/loginultimo.jpg"))); // NOI18N

        usuarioIngresar.setColumns(15);

        contrasena.setColumns(15);

        Login.setText("Iniciar Sesion");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Login)
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(usuarioIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(Login)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String usuarioTexto = usuarioIngresar.getText().trim();    //para obtener lo que el usuario escibe
        String contrasenaTexto = new String(contrasena.getPassword()).trim();
        String adminCodigo = "admin";
        String adminContrasena = "IPC1F";
        
        //Login del admin
            if (usuarioTexto.equals(adminCodigo) && contrasenaTexto.equals(adminContrasena)) {
            JOptionPane.showMessageDialog(this, "Ha ingresado como administrador", "Acceso correcto", JOptionPane.INFORMATION_MESSAGE);
            AdminView admin = new AdminView();
            admin.setVisible(true);
            this.dispose();
            return;
        }

        //login de vendedor
        // Si es vendedor (leer archivo)
        boolean vendedorEncontrado = false;
        try (BufferedReader reader = new BufferedReader(new FileReader("vendedores.txt"))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length >= 4) {
                    String codigo = datos[0].trim();
                    String nombre = datos[1].trim();
                    String genero = datos[2].trim();
                    String contrasena = datos[3].trim();

                    // Coincide código y contraseña
                    if (usuarioTexto.equalsIgnoreCase(codigo) && contrasenaTexto.equals(contrasena)) {
                        vendedorEncontrado = true;
                        JOptionPane.showMessageDialog(this, "Bienvenido, " + nombre + " (Vendedor)", "Acceso correcto", JOptionPane.INFORMATION_MESSAGE);
                        VendedorView vendedor = new VendedorView();
                        vendedor.setVisible(true);
                        this.dispose();
                        break;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo de vendedores.\nPrimero debe registrar al menos un vendedor.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //login de cliente
        boolean clienteEncontrado = false;
        try (BufferedReader reader = new BufferedReader(new FileReader("clientes.txt"))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(",");
                if (datos.length >= 5) {
                    String codigo = datos[0].trim();
                    String nombre = datos[1].trim();
                    String genero = datos[2].trim();
                    String fechaNacimiento = datos[3].trim();
                    String contrasenaCliente = datos[4].trim();

                    if (usuarioTexto.equalsIgnoreCase(codigo) && contrasenaTexto.equals(contrasenaCliente)) {
                        clienteEncontrado = true;
                        JOptionPane.showMessageDialog(this, "Bienvenido, " + nombre + " (Cliente)", "Acceso correcto", JOptionPane.INFORMATION_MESSAGE);
                        ClienteView cliente = new ClienteView();
                        cliente.setVisible(true);
                        this.dispose();
                        return;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo de clientes.\nPrimero debe registrar al menos un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Si no encontró vendedor ni cliente
        if (!vendedorEncontrado && !clienteEncontrado) {
            JOptionPane.showMessageDialog(this, "Código o contraseña incorrectos.", "Error de acceso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField usuarioIngresar;
    // End of variables declaration//GEN-END:variables
}
