package arenausac.vista;

/**
 *
 * @author Katherin Yasmin
 */
import javax.swing.*;
import java.awt.*;
import arenausac.controlador.ArenaUSAC;
import arenausac.controlador.Historial;
import arenausac.controlador.Batalla;
import arenausac.modelo.Personaje;
import arenausac.modelo.Estudiante;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

public class VentanaPrincipal extends javax.swing.JFrame {
    private ArenaUSAC arena = new ArenaUSAC(10);
    private Historial historial = new Historial(20);
    private Estudiante estudiante;
    
    private static final java.util.logging.Logger loffer = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipall
     */
    public VentanaPrincipal() {
        initComponents();
        
        //para los datos del estudiantes, se piden antes de iniciar
        String nombreEst = JOptionPane.showInputDialog(this, "Nombre del estudiante:");
        String carneEst = JOptionPane.showInputDialog(this, "Carnet:");
        estudiante = new Estudiante(nombreEst, carneEst);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnAgregarPersonaje = new javax.swing.JButton();
        btnListarPersonajes = new javax.swing.JButton();
        btnBuscarPersonaje = new javax.swing.JButton();
        btnEliminarPersonaje = new javax.swing.JButton();
        btnModificarPersonaje = new javax.swing.JButton();
        btnIniciarBatalla = new javax.swing.JButton();
        btnMostrarHistorial = new javax.swing.JButton();
        btnGuardarPersonajes = new javax.swing.JButton();
        btnCargarPersonajes = new javax.swing.JButton();
        btnGuardarHistorial = new javax.swing.JButton();
        btnDatosEstudiante = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 255));

        btnAgregarPersonaje.setText("Agregar Personaje");
        btnAgregarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonajeActionPerformed(evt);
            }
        });

        btnListarPersonajes.setText("Listar Personajes");
        btnListarPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPersonajesActionPerformed(evt);
            }
        });

        btnBuscarPersonaje.setText("Buscar Personaje");
        btnBuscarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonajeActionPerformed(evt);
            }
        });

        btnEliminarPersonaje.setText("Eliminar Personaje");
        btnEliminarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonajeActionPerformed(evt);
            }
        });

        btnModificarPersonaje.setBackground(new java.awt.Color(153, 153, 255));
        btnModificarPersonaje.setText("Modificar Personaje");
        btnModificarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonajeActionPerformed(evt);
            }
        });

        btnIniciarBatalla.setBackground(new java.awt.Color(153, 153, 255));
        btnIniciarBatalla.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarBatalla.setText("Iniciar Batalla");
        btnIniciarBatalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarBatallaActionPerformed(evt);
            }
        });

        btnMostrarHistorial.setText("Mostrar Historial");
        btnMostrarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarHistorialActionPerformed(evt);
            }
        });

        btnGuardarPersonajes.setText("Guardar Personajes");
        btnGuardarPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPersonajesActionPerformed(evt);
            }
        });

        btnCargarPersonajes.setText("Cargar Personajes");
        btnCargarPersonajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPersonajesActionPerformed(evt);
            }
        });

        btnGuardarHistorial.setText("Guardar Historial");
        btnGuardarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHistorialActionPerformed(evt);
            }
        });

        btnDatosEstudiante.setBackground(new java.awt.Color(153, 153, 255));
        btnDatosEstudiante.setText("Datos del estudiante");
        btnDatosEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMostrarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(btnListarPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCargarPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminarPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnModificarPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDatosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIniciarBatalla, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(941, 941, 941)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarBatalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarPersonaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBuscarPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListarPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminarPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnModificarPersonaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(btnCargarPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarPersonajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDatosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonajeActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = JOptionPane.showInputDialog(this, "Nombre:");
            String arma = JOptionPane.showInputDialog(this, "Arma:");
            int hp = Integer.parseInt(JOptionPane.showInputDialog(this, "HP (100-500):"));
            int ataque = Integer.parseInt(JOptionPane.showInputDialog(this, "Ataque (10-100):"));
            int velocidad = Integer.parseInt(JOptionPane.showInputDialog(this, "Velocidad (1-10):"));
            int agilidad = Integer.parseInt(JOptionPane.showInputDialog(this, "Agilidad (1-10):"));
            int defensa = Integer.parseInt(JOptionPane.showInputDialog(this, "Defensa (1-50):"));

            Personaje p = new Personaje(nombre, arma, hp, ataque, velocidad, agilidad, defensa);
            arena.agregarPersonaje(p);
            JOptionPane.showMessageDialog(this, "Personaje agregado");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarPersonajeActionPerformed

    
    private void btnListarPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPersonajesActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        for (Personaje p : arena.getListaPersonajes()) {
             if (p != null) sb.append(p.toString()).append("\n");
        }
        JTextArea text = new JTextArea(sb.toString());
        text.setEditable(false);
        JOptionPane.showMessageDialog(this, new JScrollPane(text), "Lista de Personajes", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnListarPersonajesActionPerformed

    
    private void btnBuscarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonajeActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(this, "Nombre del personaje:");
        Personaje p = arena.buscarPorNombre(nombre);
        if (p != null) {
            JOptionPane.showMessageDialog(this, p.toString(), "Encontrado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ese personaje");
        }
    }//GEN-LAST:event_btnBuscarPersonajeActionPerformed

    
    private void btnEliminarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonajeActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(JOptionPane.showInputDialog(this, "ID del personaje a eliminar:"));
        arena.eliminarPersonaje(id);
        JOptionPane.showMessageDialog(this, "Personaje eliminado");
    }//GEN-LAST:event_btnEliminarPersonajeActionPerformed

    
    private void btnModificarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonajeActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(JOptionPane.showInputDialog(this, "ID del personaje:"));
        String arma = JOptionPane.showInputDialog(this, "Nueva arma:");
        int hp = Integer.parseInt(JOptionPane.showInputDialog(this, "Nuevo HP:"));
        int ataque = Integer.parseInt(JOptionPane.showInputDialog(this, "Nuevo Ataque:"));
        int velocidad = Integer.parseInt(JOptionPane.showInputDialog(this, "Nueva Velocidad:"));
        int agilidad = Integer.parseInt(JOptionPane.showInputDialog(this, "Nueva Agilidad:"));
        int defensa = Integer.parseInt(JOptionPane.showInputDialog(this, "Nueva Defensa:"));

        arena.modificarPersonaje(id, arma, hp, ataque, velocidad, agilidad, defensa);
        JOptionPane.showMessageDialog(this, "Personaje modificado");
    }//GEN-LAST:event_btnModificarPersonajeActionPerformed

    
    
    private void btnMostrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarHistorialActionPerformed
        // TODO add your handling code here:
        JTextArea text = new JTextArea();
        historial.mostrarHistorial(text);
        JOptionPane.showMessageDialog(this, new JScrollPane(text), "Historial de batallas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMostrarHistorialActionPerformed

    
    private void btnGuardarPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPersonajesActionPerformed
        // TODO add your handling code here:
        arena.guardarPersonajes("personajes.txt");
        JOptionPane.showMessageDialog(this, "Personajes guardados");
    }//GEN-LAST:event_btnGuardarPersonajesActionPerformed

    
    private void btnCargarPersonajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPersonajesActionPerformed
        // TODO add your handling code here:
        arena.cargarPersonajes("personajes.txt");
        JOptionPane.showMessageDialog(this, "Personajes cargados");
    }//GEN-LAST:event_btnCargarPersonajesActionPerformed

    
    private void btnGuardarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHistorialActionPerformed
        // TODO add your handling code here:
        historial.guardarHistorial("historial.txt");
        JOptionPane.showMessageDialog(this, "Historial guardado");
    }//GEN-LAST:event_btnGuardarHistorialActionPerformed

    
    private void btnDatosEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosEstudianteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, estudiante.toString(), "Datos del estudiante", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDatosEstudianteActionPerformed

    private void btnIniciarBatallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarBatallaActionPerformed
        // TODO add your handling code here:
        int id1 = Integer.parseInt(JOptionPane.showInputDialog(this, "ID del primer personaje:"));
        int id2 = Integer.parseInt(JOptionPane.showInputDialog(this, "ID del segundo personaje:"));
        Personaje p1 = arena.buscarPorId(id1);
        Personaje p2 = arena.buscarPorId(id2);

        if (p1 != null && p2 != null) {
            JTextArea textArea = new JTextArea(15,40);
            new Thread(() -> {
                Batalla batalla = new Batalla(p1, p2, historial, new JTextArea(), new JProgressBar(), new JProgressBar());
                batalla.iniciar();
            }).start();
            JOptionPane.showMessageDialog(this, "Batalla iniciada");
        } else {
            JOptionPane.showMessageDialog(this, "Alguno de los personajes no existe");
        }
    }//GEN-LAST:event_btnIniciarBatallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersonaje;
    private javax.swing.JButton btnBuscarPersonaje;
    private javax.swing.JButton btnCargarPersonajes;
    private javax.swing.JButton btnDatosEstudiante;
    private javax.swing.JButton btnEliminarPersonaje;
    private javax.swing.JButton btnGuardarHistorial;
    private javax.swing.JButton btnGuardarPersonajes;
    private javax.swing.JButton btnIniciarBatalla;
    private javax.swing.JButton btnListarPersonajes;
    private javax.swing.JButton btnModificarPersonaje;
    private javax.swing.JButton btnMostrarHistorial;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}

